# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manage', '0001_initial'),
        ('tag_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('comment_count', models.IntegerField(default=0)),
                ('cover_img', models.CharField(max_length=255)),
                ('favor_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogTagRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('blog_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.BlogInfo')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_manage.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.BlogInfo'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='reply_comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.BlogComment'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manage.User'),
        ),
    ]
