# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blog_info_id',
            new_name='blog_info',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='reply_comment_id',
            new_name='reply_comment',
        ),
        migrations.RenameField(
            model_name='blogtagrelation',
            old_name='blog_info_id',
            new_name='blog_info',
        ),
        migrations.RenameField(
            model_name='blogtagrelation',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
